Stratio/crossdata

crossdata-core/src/main/java/com/stratio/crossdata/core/planner/Planner.java
This is a workaround. I'm not sure if it fits the best or not.
=> Fix: SQLDirectQuery was missing at 'planQuery' in Planner

crossdata-cassandra/pom.xml, crossdata-examples/pom.xml, crossdata-hive/pom.xml, crossdata-ng/pom.xml, pom.xml
clean pom files
comment scala-2.11 profile until we find out how to deal with it automaticallly
=> clean pom files

README.rst, crossdata-acceptance-test/pom.xml, crossdata-cassandra/src/main/scala/com/stratio/crossdata/sql/sources/cassandra/CassandraColumnRole.scala, crossdata-cassandra/src/main/scala/com/stratio/crossdata/sql/sources/cassandra/CassandraQueryProcessor.scala, crossdata-cassandra/src/main/scala/org/apache/spark/sql/cassandra/CassandraXDSourceRelation.scala, crossdata-cassandra/src/test/scala/com/stratio/crossdata/sql/sources/cassandra/CassandraQueryProcessorSpec.scala, crossdata-examples/src/main/scala/com/stratio/crossdata/examples/CassandraExample.scala, crossdata-hive/pom.xml, crossdata-ng/pom.xml, crossdata-ng/src/main/scala/com/stratio/crossdata/sql/sources/interfaces.scala, crossdata-ng/src/main/scala/org/apache/spark/sql/crossdata/XDDataFrame.scala, crossdata-ng/src/main/scala/org/apache/spark/sql/sources/CatalystToCrossdataAdapter.scala, crossdata-ng/src/main/scala/org/apache/spark/sql/sources/crossdata/CatalystToCrossdataAdapter.scala, crossdata-ng/src/test/scala/org/apache/spark/sql/crossdata/XDDataFrameSpec.scala, crossdata-ng/src/test/scala/org/apache/spark/sql/crossdata/XDDataFrameUtilsSpec.scala, pom.xml
-Added pushdown interface
-New kind of filters supported by the native connector apart from CKs filters
-Fix several typos
=> CROSSDATA-818 CROSSDATA-819 improve native interface and cassandra implementation

crossdata-cassandra/pom.xml
The new version has critical performance improvements
=> Upgrade cassandra connector

crossdata-common/pom.xml, crossdata-common/src/main/scala/com/stratio/crossdata/common/Message.scala, crossdata-hive/pom.xml, pom.xml
New module created for new Akka architecture
=> Crossdata Commond module created

crossdata-tests/pom.xml, crossdata-tests/src/test/resources/crossdatang/BasicCassandra.feature, crossdata-tests/src/test/resources/crossdatang/BasicJoinCassandra.feature, crossdata-tests/src/test/scala/cassandra/CassandraTestUtils.scala, crossdata-tests/src/test/scala/crossdatang/SimpleSelectTest.scala, pom.xml
=> New acceptance test

crossdata-common/src/main/scala/com/stratio/crossdata/common/metadata/FieldMetadata.scala, crossdata-common/src/main/scala/org/apache/spark/sql/crossdata/metadata/DataTypesUtils.scala, crossdata-driver/src/main/scala/com/stratio/crossdata/driver/Driver.scala, crossdata-driver/src/test/scala/com/stratio/crossdata/driver/DriverIT.scala
Some implementations are blocked by a persistent metastore
=> DriverAPI for JDBC/ODBC

crossdata-cassandra/src/test/scala/com/stratio/crossdata/sql/sources/cassandra/CassandraConnectorIT.scala, crossdata-driver/src/main/resources/reference.conf, crossdata-driver/src/test/scala/com/stratio/crossdata/driver/DriverIT.scala, pom.xml
-Upgrade Akka to Spark version (2.3.11)
-Update Spark to 1.5.1
-Workaround in failed tests
=> Update toSpark 1.5.1

CHANGELOG.md
Added the current release features to the changeLog.md file
=> [CROSSDATA-7] [DOC] Release Notes

doc/src/site/sphinx/7_crossdata_production.rst
Adds Crossdata Production checklist to documentation
=> [CROSSDATA-14] [Documentation] Production checklist & TroubleShooting guide

doc/src/site/sphinx/11_crossdata_faqs.rst
Added FAQ section. It could be expanded or edited in the future.
=> CROSSDATA-12 [DOC] Added FAQ document section

doc/src/site/sphinx/13_other_modules.rst
Added section describing the interaction of Crossdata with other modules within the platform.
=> CROSSDATA-13 [DOC] Added "other modules" section.

doc/src/site/sphinx/2_getting_started.rst
First getting started document with info abot how to install crossdata, run it, and execute an example.
=> [CROSSDATA-4] [DOC] Getting Started document

common/src/main/scala/com/stratio/crossdata/common/result/SQLResult.scala, driver/src/test/scala/com/stratio/crossdata/driver/DriverSpec.scala, pom.xml
- Crossdata parent dependency updated
- Incorrect test fixed. It might imply some changes, review TODO comment.
=> Minor changes

driver/src/main/resources/driver-reference.conf, driver/src/main/scala/com/stratio/crossdata/driver/Driver.scala, driver/src/main/scala/com/stratio/crossdata/driver/JavaDriver.scala, driver/src/main/scala/com/stratio/crossdata/driver/config/DriverConfig.scala
Change Crossdata driver to allow external driver-application.conf file with configuration properties
=> [CROSSDATA-77] [DRIVER] Allow external properties file for Crossdata Driver

testAT/src/test/resources/features/manual/combinedQueries.feature, testAT/src/test/resources/features/manual/metadataOperations.feature, testAT/src/test/resources/features/manual/multipleConnectors.feature, testAT/src/test/resources/features/manual/nativeConnectorQueries.feature, testAT/src/test/resources/features/manual/queriesOperations.feature, testAT/src/test/resources/features/manual/storageOperations.feature
first attempt of creating tests
=> first approach to tests

elasticsearch/pom.xml, scripts/make-distribution-crossdata.sh, scripts/stratio-xd-shell
Fixed make-distribution script by adding fat jars and removing conflict files
=> [CROSSDATA-90][Script] Fixed make-distribution 

testsAT/src/test/resources/features/manual/storageOperations.feature
CROSSDATA-104 CROSSDATA-105 add storage operations
=> CROSSDATA-104 CROSSDATA-105 add storage operations

README.rst, core/pom.xml, doc/src/site/sphinx/0_feature_guide.rst, doc/src/site/sphinx/2_getting_started.rst, pom.xml
Before adding a getting started, we should define how manage server dependencies. So, this section should not be taken into account.
=> [DOC] Minor improvements

core/src/main/scala/org/apache/spark/sql/crossdata/XDCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/DerbyCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/JDBCCatalog.scala, core/src/test/scala/org/apache/spark/sql/crossdata/catalog/JDBCCatalogIT.scala
Now SHOW TABLES returns true if the table is persisted in the XD Catalog
=> [CROSSDATA-168][CATALOG] Fixed SHOW TABLES

cassandra/src/main/scala/org/apache/spark/sql/cassandra/CassandraXDSourceRelation.scala, cassandra/src/test/scala/com/stratio/crossdata/connector/cassandra/CassandraAggregationIT.scala, core/src/main/scala/org/apache/spark/sql/crossdata/XDDataFrame.scala
Fixed C* datasource Row types.
=> CROSSDATA-169: fixed cassandra native types

mongodb/src/main/scala/com/stratio/crossdata/connector/mongodb/MongoQueryProcessor.scala, mongodb/src/test/scala/com/stratio/crossdata/connector/mongodb/MongoFilterIT.scala, mongodb/src/test/scala/com/stratio/crossdata/connector/mongodb/MongoQueryProcessorSpec.scala, mongodb/src/test/scala/com/stratio/crossdata/connector/mongodb/MongoWithSharedContext.scala
* Support NOT filter by collect(spark)
=> [CROSSDATA-162] [Mongo Connector tasks] Support for modifier NOT

cassandra/src/test/scala/com/stratio/crossdata/connector/cassandra/CassandraWithSharedContext.scala, core/src/test/scala/org/apache/spark/sql/crossdata/test/SharedXDContextWithDataTest.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticWithSharedContext.scala, mongodb/src/test/scala/com/stratio/crossdata/connector/mongodb/MongoWithSharedContext.scala
Created template pattern trait which provides a minimal method set to implement by those datasources tests which require pre-loaded data. Exemplified its use in the main cassandra connector test.
=> Unified type tests

elasticsearch/src/main/scala/com/stratio/crossdata/connector/elasticsearch/ElasticSearchRowConverter.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticsearchConnectorIT.scala
=> [CROSSDATA-173] [Elasticsearch] Fix Bug with Date Type

doc/src/site/sphinx/connectors/mongodb_connector.rst, mongodb/src/main/scala/com/stratio/crossdata/connector/mongodb/DefaultSource.scala, mongodb/src/test/scala/com/stratio/crossdata/connector/mongodb/MongoImportTablesIT.scala
Import specific collections or databases from MongoDB to Crossdata.
=> [CROSSDATA-40] [Mongo Connector] Import table(Mongo) 

core/src/main/scala/org/apache/spark/sql/crossdata/metrics/XDMetricsSource.scala, server/src/main/resources/server-reference.conf, server/src/main/resources/xdmetrics.properties
=> [CROSSDATA-187][Server & Core] JMX metrics

driver/src/main/scala/com/stratio/crossdata/driver/Driver.scala, driver/src/main/scala/com/stratio/crossdata/driver/actor/ProxyActor.scala
Bug in Driver, added the close method, this make one shutdown in the actor system.
@darroyocazorla  
All passed.
=> [CROSSDATA-145] [DRIVER] Bug corrected for close the actor system

core/src/main/scala/org/apache/spark/sql/crossdata/XDCatalog.scala, core/src/test/scala/org/apache/spark/sql/crossdata/test/SharedXDContextTypesTest.scala, core/src/test/scala/org/apache/spark/sql/crossdata/test/SharedXDContextWithDataTest.scala
The comments should serve as a guide to implement new tests.
=> Commented test templates and removed some warnings.

core/src/main/scala/org/apache/spark/sql/crossdata/package.scala, driver/src/main/scala/com/stratio/crossdata/driver/shell/BasicShell.scala, sandbox/stratio_sandbox_module, scripts/stratio-xd-init.scala, scripts/stratio-xd-shell, server/src/main/resources/server-reference.conf, server/src/main/scala/com/stratio/crossdata/server/CrossdataServer.scala
=> Referenced version update

.gitignore, driver/src/main/resources/driver-reference.conf, driver/src/main/scala/com/stratio/crossdata/driver/shell/BasicShell.scala
* Save & load history
* Deal with annoying message of the Akka Cluster in the initialization
=> [CROSSDATA-229] [SHELL] Persistent history implemented

core/pom.xml, core/src/main/resources/core-reference.conf, core/src/main/scala/org/apache/spark/sql/crossdata/XDContext.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/JDBCCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/XDCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/ZookeeperCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/config/CoreConfig.scala, core/src/main/scala/org/apache/spark/sql/crossdata/daos/DAOConstants.scala, core/src/main/scala/org/apache/spark/sql/crossdata/daos/EphemeralTableDAOComponent.scala, core/src/main/scala/org/apache/spark/sql/crossdata/daos/StreamingQueriesDAOComponent.scala, core/src/main/scala/org/apache/spark/sql/crossdata/daos/TableDAOComponent.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/ConnectionHostModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/EphemeralExecutionStatus.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/EphemeralOptionsModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/EphemeralStatusModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/EphemeralTableModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/KafkaOptionsModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/StreamingQueryModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/TableModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/TopicModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/serializers/CrossdataSerializer.scala, core/src/test/resources/core-reference.conf, core/src/test/resources/zookeeper-catalog.conf, core/src/test/scala/org/apache/spark/sql/crossdata/catalog/CatalogConstants.scala, core/src/test/scala/org/apache/spark/sql/crossdata/catalog/DerbyCatalogIT.scala, core/src/test/scala/org/apache/spark/sql/crossdata/catalog/GenericCatalogTests.scala, core/src/test/scala/org/apache/spark/sql/crossdata/catalog/ZookeeperCatalogIT.scala, core/src/test/scala/org/apache/spark/sql/crossdata/test/SharedXDContextTest.scala, core/src/test/scala/org/apache/spark/sql/crossdata/test/TestXDContext.scala, pom.xml
- Added zookeeper repository as a persisted catalog.
- Added models for serialization with zookeeper repository.
- Added config as input param into crossdataContext.
- Changed JDDBC test to Derby test and all test are in one trait that must be passed with all catalog integration tests. 
@pfcoperez 
All passed.
Added integration test with Zookeeper dependency.
=> [CROSSDATA-148] [CORE] Zookeeper catalog

server/src/main/resources/server-reference.conf
Fix DriverIT test by updating server version
=> Update server jar in server-reference

core/src/main/scala/org/apache/spark/sql/crossdata/XDDataFrame.scala, core/src/test/scala/org/apache/spark/sql/crossdata/test/SharedXDContextTypesTest.scala
Enables flattened collect for LIMIT-like SQLs
=> Flattened with limit

driver/src/test/scala/com/stratio/crossdata/driver/DriverIT.scala, driver/src/test/scala/com/stratio/crossdata/driver/JavaDriverIT.scala
Actually it's working, JavaDriverIT added to test it.
=> [CROSSDATA-197] [DRIVER] JavaDriver constructor does not read the config

cassandra/pom.xml
Spark-Cassandra-Connector version updated from 1.5.0-M3 to 1.5.0-RC1
=> Spark-Cassandra-Connector version updated

core/src/main/scala/org/apache/spark/sql/crossdata/XDContext.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/EphemeralOptionsModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/EphemeralOutputFormat.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/EphemeralQueryModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/EphemeralStatusModel.scala, streaming/src/main/scala/com/stratio/crossdata/streaming/CrossdataStreaming.scala, streaming/src/main/scala/com/stratio/crossdata/streaming/CrossdataStreamingApplication.scala, streaming/src/main/scala/com/stratio/crossdata/streaming/actors/EphemeralStatusActor.scala, streaming/src/main/scala/com/stratio/crossdata/streaming/helpers/CrossdataStatusHelper.scala
CROSSDATA-293
CROSSDATA-294
CROSSDATA-295
=> [CROSSDATA-152] [STREAMING] [CORE] Close correctly with statuses, initial XDContext and Window operation

cassandra/src/main/scala/com/stratio/crossdata/connector/cassandra/statements/CreateTableStatement.scala
Removed perfectly working imperative code just for the sake of keeping the functional style
=> Changes a code snippet from imperative to functional

core/src/main/scala/org/apache/spark/sql/crossdata/models/EphemeralQueryModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/KafkaOptionsModel.scala, streaming/src/main/scala/com/stratio/crossdata/streaming/constants/KafkaConstants.scala, streaming/src/main/scala/com/stratio/crossdata/streaming/helpers/CrossdataStreamingHelper.scala
Kafka partitions in producer defined in ephemeral table and in ephemeral query
=> [CROSSDATA-287] [STREAMING] [CORE] Kafka partitions options

driver/pom.xml
@luismcl please, review this PR in order to check if I'm breaking something :-)
=> Name of the executable file for the shell changed

zeppelin/.gitignore, zeppelin/README.md, zeppelin/files/zeppelin-site.xml, zeppelin/pom.xml, zeppelin/scripts/add-crossdata-interpreter.sh, zeppelin/src/main/java/org/apache/zeppelin/crossdata/CrossdataInterpreter.java
Added an interpreter as a module within crossdata
=> [CROSSDATA-236] Zeppelin interpreter

core/src/main/scala/org/apache/spark/sql/crossdata/XDContext.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/MySQLCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/PostgreSQLCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/ZookeeperCatalog.scala
This SHOULD BE REVIEWED, it is a temporary solution with sinister traits.
=> Quick fix enabling XDContext serialization when distributing jobs

core/src/main/scala/org/apache/spark/sql/crossdata/catalog/PostgreSQLCatalog.scala
=> [CROSSDATA-325]  [CORE] Implement persistence layer (Postgre)

core/src/main/scala/org/apache/spark/sql/crossdata/config/StreamingConfig.scala, core/src/main/scala/org/apache/spark/sql/crossdata/execution/datasources/XDDdlParser.scala, core/src/main/scala/org/apache/spark/sql/crossdata/execution/datasources/streamingDdl.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/EphemeralTableModel.scala, streaming/src/main/scala/com/stratio/crossdata/streaming/CrossdataStreamingApplication.scala
Schema added again to the ephemeral table sentence.
Support for several ephemeral tables from config file.
=> Ephemeral table with schema

server/pom.xml
http://stackoverflow.com/questions/17265002/hadoop-no-filesystem-for-scheme-file
=> Fix bug with HDFS of the Server fat jar

pom.xml
https://github.com/apache/spark/pull/5041
@darroyocazorla and @jjlopezm please, review this PR that has been suggested by @luismcl
=> Avoid problem with SPARK-4820

core/src/test/scala/com/stratio/crossdata/test/BaseXDTest.scala, streaming/src/test/scala/com/stratio/crossdata/streaming/actors/EphemeralQueryActorIT.scala, streaming/src/test/scala/com/stratio/crossdata/streaming/actors/EphemeralStatusActorIT.scala, streaming/src/test/scala/com/stratio/crossdata/streaming/test/BaseSparkStreamingXDTest.scala
=> [CROSSDATA] [STREAMING] Time limit for Integration Tests of Streaming

README.rst
=> [CROSSDATA-383] Link to documentation in README.rst is outdated

mongodb/pom.xml, mongodb/src/main/scala/com/stratio/crossdata/connector/mongodb/DefaultSource.scala, mongodb/src/main/scala/com/stratio/crossdata/connector/mongodb/MongoQueryProcessor.scala, mongodb/src/main/scala/com/stratio/crossdata/connector/mongodb/MongodbConnection.scala, mongodb/src/main/scala/com/stratio/crossdata/connector/mongodb/MongodbXDRelation.scala, mongodb/src/test/scala/com/stratio/crossdata/connector/mongodb/MongoImportTablesIT.scala, mongodb/src/test/scala/com/stratio/crossdata/connector/mongodb/MongoQueryProcessorSpec.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/MongoWithSharedContext.scala
This PR adapt Crossdata to the latest version of Spark Mongo Data Source (0.11.1)
=> [CROSSDATA-413] Adapt Crossdata to the last version of the Spark-MongoDB datasource

server/src/main/scala/com/stratio/crossdata/server/actors/JobActor.scala
Added an executor class which creates a dedicated one-use thread for each command.
Used to build an non-pooled ExecutorContext.
=> [CROSSDATA-418] Dedicated threads for spark driver program execution within the server JVM

core/src/main/scala/org/apache/spark/sql/crossdata/execution/datasources/XDDdlParser.scala, core/src/main/scala/org/apache/spark/sql/crossdata/execution/datasources/ddl.scala, driver/src/main/scala/com/stratio/crossdata/driver/Driver.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/DriverDdlIT.scala
Add command DROP ALL TABLES to grammar and driver using the dropAllTables logic existent
=> [CROSSDATA-382]Implement DROP ALL TABLES from SQL

core/src/main/scala/org/apache/spark/sql/crossdata/XDContext.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/DerbyCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/MySQLCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/PostgreSQLCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/XDCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/ZookeeperCatalog.scala, driver/src/main/scala/com/stratio/crossdata/driver/Driver.scala, server/src/main/scala/com/stratio/crossdata/server/CrossdataServer.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/DriverDdlIT.scala
This PR check the connection with the catalog at the moment of start server. If the catalog is not reachable, the server fail at start.
=> [CROSSDATA-372] Server should check the catalog connection when it is started

core/src/main/scala/org/apache/spark/sql/crossdata/XDDataFrame.scala
This PR solve the problem of columns of type ArrayType that contains StructType inside.
=> Fix flatten columns with Array of StructType

driver/src/main/unix/files_and_dirs/DEBIAN/conffiles, driver/src/main/unix/scripts/post, driver/src/main/unix/scripts/postinst
This PR solve the problems with the configuration path when create a package with the shell
=> Fix conf path of shell

core/src/main/scala/org/apache/spark/sql/crossdata/config/StreamingConfig.scala, core/src/main/scala/org/apache/spark/sql/crossdata/execution/datasources/streamingDdl.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/ConnectionModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/models/KafkaOptionsModel.scala, core/src/test/scala/org/apache/spark/sql/crossdata/catalog/ZookeeperStreamingCatalogIT.scala, core/src/test/scala/org/apache/spark/sql/crossdata/config/StreamingConfigSpec.scala, streaming/src/main/scala/com/stratio/crossdata/streaming/kafka/KafkaInput.scala, streaming/src/main/scala/com/stratio/crossdata/streaming/kafka/KafkaProducer.scala, streaming/src/test/scala/com/stratio/crossdata/streaming/kafka/KafkaProducerSpec.scala, streaming/src/test/scala/com/stratio/crossdata/streaming/test/CommonValues.scala
The problem was that only one Zookeeper host and only one Kafka host were used to connect to both system. This PR solves the problem
=> [CROSSDATA] [STREAMING] Fix problem with Streaming configuration

pom.xml
To match Spark's dependency version.
=> [CROSSDATA-363] Derby version downgrade

dist/pom.xml, streaming/pom.xml
=> [CROSSDATA] [STREAMING] ES dependency removed

core/src/main/scala/com/stratio/crossdata/launcher/SparkJobLauncher.scala, streaming/src/main/scala/com/stratio/crossdata/streaming/CrossdataStreaming.scala, streaming/src/main/scala/com/stratio/crossdata/streaming/CrossdataStreamingApplication.scala
Fix map serialization
Use the proper zookeeper config path
=> Solve streaming issues

streaming/src/test/scala/com/stratio/crossdata/streaming/test/BaseSparkStreamingXDTest.scala, streaming/src/test/scala/com/stratio/crossdata/streaming/test/BaseStreamingXDTest.scala, streaming/src/test/scala/com/stratio/crossdata/streaming/test/CommonValues.scala, streaming/src/test/scala/org/apache/spark/streaming/kafka/CrossdataStreamingHelperProjectIT.scala, streaming/src/test/scala/org/apache/spark/streaming/kafka/CrossdataStreamingHelperSelectIT.scala, streaming/src/test/scala/org/apache/spark/streaming/kafka/KafkaStreamIT.scala
This PR add streaming integration tests end to end with kafka and zookeeper from Spark tests suite.
=> [CROSSDATA-426] [Streaming] Expand Streaming Tests

elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticWithSharedContext.scala, streaming/src/test/scala/org/apache/spark/streaming/kafka/CrossdataStreamingHelperSelectIT.scala
Flush index after indexing data
=> Fix elasticsearch tests

core/src/main/resources/core-reference.conf, core/src/main/scala/org/apache/spark/sql/crossdata/XDContext.scala, core/src/main/scala/org/apache/spark/sql/crossdata/XDDataFrame.scala, core/src/main/scala/org/apache/spark/sql/crossdata/security/AuthorizationReply.scala, core/src/main/scala/org/apache/spark/sql/crossdata/security/Credentials.scala, core/src/main/scala/org/apache/spark/sql/crossdata/security/DefaultSecurityManager.scala, core/src/main/scala/org/apache/spark/sql/crossdata/security/SecurityManager.scala, core/src/test/resources/core-reference.conf, core/src/test/scala/org/apache/spark/sql/crossdata/security/DummySecurityManager.scala, core/src/test/scala/org/apache/spark/sql/crossdata/security/SecurityManagerIT.scala, dist/src/main/resources/server/core-application.conf
This PR adds a basic trait of a Security Manager and a default implementation. This lets to add authorization operations and include more information into the logs.
Documentation available here: https://stratio.atlassian.net/wiki/display/CROSSDATA/Security#Security-SecurityManager
=> [CROSSDATA-467] [SECURITY] Security Manager added

core/src/main/scala/org/apache/spark/sql/crossdata/catalog/persistent/PersistentCatalogWithCache.scala
Persisted plans are now cached before being processed (wrapped in a `Subquery` plan node and, optionally, by an alias). This wrapping is posponed to look-up time.
- Acceptance tests
=> Plans are now cached before being processed.

CHANGELOG.md, driver/pom.xml, server/pom.xml
This PR fixes the multiples slf4j that have been server and driver.
=> [CROSSDATA-495] Multiple logger implementations are being packaged

dist/src/main/resources/server/core-application.conf, dist/src/main/unix/scripts/post, dist/src/main/unix/scripts/postinst
Resource parameters of Add/execute app command added to dist
=> Resource parameters of Add/execute app command added to dist

.gitignore, cassandra/pom.xml, cassandra/src/main/scala/com/stratio/crossdata/connector/cassandra/CassandraQueryProcessor.scala, cassandra/src/main/scala/org/apache/spark/sql/cassandra/CassandraXDSourceRelation.scala, cassandra/src/test/scala/com/stratio/crossdata/connector/cassandra/CassandraConnectorIT.scala, cassandra/src/test/scala/com/stratio/crossdata/connector/cassandra/CassandraCreateExternalTableIT.scala, cassandra/src/test/scala/com/stratio/crossdata/connector/cassandra/CassandraWithSharedContext.scala, common/pom.xml, core/pom.xml, dist/pom.xml, driver/pom.xml, elasticsearch/pom.xml, mongodb/pom.xml, pom.xml, server/pom.xml, streaming/pom.xml, testsIT/pom.xml
- Upgrade of Cassandra & ES datasource
- Scala cross build changed from 2.11 to 2.10
=> Upgrade of datasources for release 1.3.0

cassandra/pom.xml, common/pom.xml, core/pom.xml, dist/pom.xml, driver/pom.xml, elasticsearch/pom.xml, examples/pom.xml, mongodb/pom.xml, pom.xml, server/pom.xml, streaming/pom.xml, testsAT/pom.xml, testsIT/pom.xml, zeppelin/pom.xml
- Crossdata versions changed from 1.3.X to 1.4.X
=> Versions in pom files changed

cassandra/pom.xml, common/pom.xml, core/pom.xml, dist/pom.xml, driver/pom.xml, elasticsearch/pom.xml, mongodb/pom.xml, pom.xml, server/pom.xml, streaming/pom.xml, testsAT/pom.xml, testsIT/pom.xml, zeppelin/pom.xml
- Upgrade to Spark 2.0.0-preview
- Upgrade of pom versions
- Upgrade of Akka version to 2.4.7
=> [CROSSDATA] Some upgrades for Spark 2

server/src/main/scala/com/stratio/crossdata/server/actors/JobActor.scala
This PR avoids to propagate the type of the exception in the error message
=> [CROSSDATA] [SERVER] #587 Cause without exception

testsIT/src/test/scala/com/stratio/crossdata/driver/DriverIT.scala
Test checking that the type exception is not included in the error message anymore
=> [CROSSDATA] [SERVER] Tests for #587

pom.xml
Upgrade to Spark version 1.6.2
=> [CROSSDATA] [UPGRADE] Upgrade to spark 1.6.2

core/src/main/scala/org/apache/spark/sql/crossdata/XDContext.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/CatalogChain.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/ExternalCatalogAPI.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/XDCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/interfaces/catalogs.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/persistent/DerbyCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/persistent/MySQLXDCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/persistent/PersistentCatalogWithCache.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/persistent/PostgreSQLXDCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/persistent/ZookeeperCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/analysis/crossdataRules.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/globalindex/IndexUtils.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/optimizer/XDOptimizer.scala, core/src/main/scala/org/apache/spark/sql/crossdata/execution/datasources/XDDdlParser.scala, core/src/main/scala/org/apache/spark/sql/crossdata/execution/datasources/ddl.scala, core/src/test/scala/org/apache/spark/sql/crossdata/catalog/GenericCatalogTests.scala, elasticsearch/src/main/scala/com/stratio/crossdata/connector/elasticsearch/DefaultSource.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticInsertCollection.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/MongoCreateGlobalIndexIT.scala
Make code easier to read
Index take into account nullable fields
=> [CROSSDATA-250][CROSSDATA-488][global index] refactor to keep xdcontext simple

examples/pom.xml, testsAT/pom.xml, zeppelin/pom.xml
Some changes of version in pom files
=> [CROSSDATA] Preparation for release 1.4.0

CHANGELOG.md, README.md, pom.xml
=> [QA-130] added coveralls badge

dist/src/main/resources/server/hazelcast.xml
=> Added Hazelcast cluster config(seed)

CHANGELOG.md
Doc links:
https://stratio.atlassian.net/wiki/display/CROSSDATA/Introduction
https://stratio.atlassian.net/wiki/display/CROSSDATA/Features 
https://stratio.atlassian.net/wiki/display/CROSSDATA/Configuration
=> [CROSSDATA-547] [Session US] Add changelog and doc

.jenkins.yml, testsIT/src/test/scala/com/stratio/crossdata/driver/DriverIT.scala
=> start ES ASAP

.jenkins.yml, testsIT/src/test/scala/com/stratio/crossdata/driver/DriverIT.scala
=> Revert "start ES ASAP"

driver/src/main/scala/com/stratio/crossdata/driver/Driver.scala, driver/src/main/scala/com/stratio/crossdata/driver/JavaDriver.scala, driver/src/main/scala/com/stratio/crossdata/driver/session/SessionManager.scala
For security reasons, in some cases, only the user will be provided in the driver
=> Only a user is passed in driver and password is optional

.jenkins.yml, .travis.yml, cassandra/pom.xml, common/pom.xml, core/pom.xml, dist/pom.xml, driver/pom.xml, elasticsearch/pom.xml, mongodb/pom.xml, pom.xml, server/pom.xml, streaming/pom.xml, testsIT/pom.xml, testsIT/src/test/scala/com/stratio/crossdata/driver/DriverIT.scala
=> [CROSSDATA-553] Set scala binary version to 2.11 by default

.jenkins.yml
Changes needed so that acceptance tests are being run against crossbuilt crossdata versions.
=> AT services and parameters from crossdataAT.groovy

.jenkins.yml
=> Restored crossbuild with a single target: Scala 2.11

server/src/main/resources/server-reference.conf, server/src/main/scala/com/stratio/crossdata/server/config/ServerConfig.scala
=> [CROSSDATA-569] Make seeds configurable through env var

dist/src/main/resources/server/server-application.conf, docker/docker-entrypoint.sh
=> [CROSSDATA-569]Trying to have docker working again

docker/docker-entrypoint.sh
=> [CROSSDATA-569]Entrypoint with new environmental var XD_EXTERNAL_IP

docker/docker-entrypoint.sh
Added memory, commented hazelcast (default 127.0.0.1) until Autodiscovery is finished.
=> [CROSSDATA-569]Feature/docker marathon support

docker/docker-entrypoint.sh
=> [CROSSDATA-556]Feature/docker marathon support

server/src/main/scala/com/stratio/crossdata/server/CrossdataServer.scala
Fixes problem related to https://github.com/Stratio/Crossdata/pull/643
=> [CROSSDATA-577] Service discovery: Bug fixing

docker/docker-entrypoint.sh
Prefix intro docker entry point for multi tentant
=> [CROSSDATA-556]Feature/docker catalog ports

docker/docker-entrypoint.sh
=> [CROSSSDATA-569]Changed to persistent class

server/src/main/scala/com/stratio/crossdata/server/CrossdataServer.scala
It follows https://github.com/Stratio/Crossdata/pull/643
=> [CROSSDATA-577] Service discovery: Solves issue with local hazelcast member

server/src/test/scala/com/stratio/crossdata/server/CrossdataDdlIT.scala
Bug fix for CrossdataDdlIT related to path for cars.csv
=> Bug fix for CrossdataDdlIT

server/src/main/scala/com/stratio/crossdata/server/CrossdataServer.scala, server/src/main/scala/org/apache/spark/sql/crossdata/session/HazelcastSessionProvider.scala
It fixes problem with addresses of Hazelcast members:
- It excludes itself as member from the configuration file
- It adds its public address to the configuration file
=> [CROSSDATA-642] Service discovery: improvements in Hazelcast members

driver/src/main/scala/com/stratio/crossdata/driver/config/DriverConf.scala
This PR solves the problem described in https://stratio.atlassian.net/browse/CROSSDATA-650
=> [CROSSDATA-650][DRIVER]Dirty result for new session - different seed

dist/src/main/resources/server/server-application.conf, docker/docker-entrypoint.sh, server/src/main/resources/server-reference.conf
Changing the spark UI port when running in marathon
=> [CROSSDATA-644]Spark configuration for 4040 port UI

server/pom.xml
Upgrade Hazelcast version to 3.7.1
=> Upgrade Hazelcast version to 3.7.1

core/src/main/scala/org/apache/spark/sql/crossdata/catalog/CatalogChain.scala
This PR removes duplicates when listing relations from multiple catalogs.
=> [CROSSDATA-654] Fix duplicate entries when listing relations from several catalogs.

core/src/main/scala/org/apache/spark/sql/crossdata/XDContext.scala, core/src/test/scala/org/apache/spark/sql/crossdata/XDContextIT.scala
Added statically defined `to_number` UDF.
=> [CROSSDATA-648] Added statically defined `to_number` UDF

core/src/main/scala/org/apache/spark/sql/crossdata/XDSession.scala, core/src/main/scala/org/apache/spark/sql/crossdata/session/XDSharedState.scala
=> [CROSSDATA-658] Mark XDSession fields as transient

core/src/test/scala/org/apache/spark/sql/crossdata/XDContextIT.scala, elasticsearch/src/main/scala/org/elasticsearch/spark/sql/ElasticsearchXDRelation.scala
=> Code cleaning & warning removal

docker/docker-entrypoint.sh
=> [CROSSDATA-644]Bind host

pom.xml
Sometimes you are lucky enough to meet some of the best developers I've ever known in Spain...
If they ( that convert Big Data into a child's play) taught you in the most demonic dark arts such as functional programming, scala, akka, elasticsearch, spark, etc... 
The only thing you can say is ¡¡Thank you!!
You are great!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Long live Crossdata!!!!!!!!!!!!
=> Added developer

core/src/main/scala/org/apache/spark/sql/crossdata/catalog/persistent/ZookeeperCatalog.scala, core/src/test/scala/org/apache/spark/sql/crossdata/catalog/persistent/ZookeeperCatalogIT.scala
- Fixed ZookeeperCatalog tests which were not testing that catalog at all.
- Fixed table and views deletions.
=> [CROSSDATA-671] Zookeeper fixes

testsAT/pom.xml, zeppelin/pom.xml
Some automatization for pom files
=> [CROSSDATA] Getting rid of some manual changes

common/pom.xml, common/src/main/scala/com/stratio/crossdata/common/messages.scala, core/src/main/scala/org/apache/spark/sql/crossdata/session/XDSessionProvider.scala, driver/src/main/scala/com/stratio/crossdata/driver/Driver.scala, driver/src/main/scala/com/stratio/crossdata/driver/actor/ProxyActor.scala, pom.xml, server/pom.xml, server/src/main/scala/com/stratio/crossdata/server/CrossdataServer.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala, server/src/main/scala/org/apache/spark/sql/crossdata/session/HazelcastSessionProvider.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/DriverIT.scala
This PR lets the driver to get also information about the cluster state of the session provider.
=> [CROSSDATA-678] [DRIVER] ClusterStateReply expanded

core/src/main/scala/com/stratio/crossdata/security/CrossdataSecurityManager.scala, core/src/main/scala/com/stratio/crossdata/security/Result.scala, core/src/main/scala/org/apache/spark/sql/crossdata/XDContext.scala, core/src/main/scala/org/apache/spark/sql/crossdata/execution/XDQueryExecution.scala, core/src/test/scala/org/apache/spark/sql/crossdata/authorizer/XDAuthorizationIT.scala, core/src/test/scala/org/apache/spark/sql/crossdata/execution/auth/AuthDirectivesExtractorIT.scala
=> [CROSSDATA-559][FOLLOW-UP] Fix some typos

common/src/main/scala/com/stratio/crossdata/common/result/responses.scala, common/src/main/scala/com/stratio/crossdata/common/serializers/CommandSerializer.scala, common/src/main/scala/com/stratio/crossdata/common/serializers/CrossdataSerializer.scala, common/src/main/scala/com/stratio/crossdata/common/serializers/FiniteDurationSerializer.scala, common/src/main/scala/com/stratio/crossdata/common/serializers/SQLResultSerializer.scala, common/src/test/scala/com/stratio/crossdata/common/serializers/CommandSerializerSpec.scala, driver/src/main/scala/com/stratio/crossdata/driver/Driver.scala, driver/src/main/scala/com/stratio/crossdata/driver/HttpDriver.scala, driver/src/main/scala/com/stratio/crossdata/driver/JavaDriver.scala, driver/src/main/scala/com/stratio/crossdata/driver/exceptions/TLSInvalidAuthException.scala, driver/src/main/scala/com/stratio/crossdata/driver/util/HttpClient.scala, server/src/main/scala/com/stratio/crossdata/server/CrossdataHttpServer.scala, server/src/main/scala/com/stratio/crossdata/server/CrossdataServer.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/TLSAuthInvalidCertificateIT.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/TLSAuthValidCertificateIT.scala
Improvements & fixes to the feature source branch.
=> Http polishing

testsAT/src/test/resources/features/Elasticsearch/ElasticSearchSelectGreaterEqualsFilter.feature, testsAT/src/test/resources/features/Elasticsearch/ElasticSearchSelectINFilter.feature, testsAT/src/test/resources/features/Elasticsearch/ElasticSearchSelectLessEqualsFilter.feature, testsAT/src/test/resources/features/Elasticsearch/ElasticSearchSelectSimple.feature, testsAT/src/test/resources/features/Elasticsearch/TemporaryViews.feature, testsAT/src/test/resources/features/Elasticsearch/Views.feature, testsAT/src/test/resources/features/MicroStrategy/MicroStrategy.feature
Added ignore aspect and till fixed for failing acceptance tests
=> Added ignore aspect and till fixed for failing acceptance tests

driver/src/main/scala/com/stratio/crossdata/driver/Driver.scala, driver/src/main/scala/com/stratio/crossdata/driver/session/SessionManager.scala
=> Keep Authentication class private to Crossdata

pom.xml, postgresql/pom.xml, postgresql/src/main/resources/META_INF.services/org.apache.spark.sql.sources.DataSourceRegister, postgresql/src/main/scala/com/stratio/crossdata/connector/postgresql/DefaultSource.scala, postgresql/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/PostgresqlUtils.scala, postgresql/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/PostgresqlXDRelation.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlConnectorIT.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlWithSharedContext.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/TestPostgresqlDriverIT.scala
Access using spark jdbc DataSource
=> [CROSSDATA-694] Create postgresql Module with postgresqlXDRelation

server/src/main/resources/server-reference.conf, server/src/main/scala/com/stratio/crossdata/server/CrossdataHttpServer.scala, server/src/main/scala/com/stratio/crossdata/server/CrossdataServer.scala, server/src/main/scala/com/stratio/crossdata/server/config/ServerConfig.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/TLSAuthInvalidCertificateIT.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/TLSAuthNoCertificateIT.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/TLSAuthValidCertificateIT.scala
This PR improves HTTP configuration settings by unifying them under the same config root.
It also enables the HTTP binding host option and unifies HTTP & HTTPS addresses into the same one.
=> HTTP Config refactor and clusterization under the same group.

.jenkins.yml
=> [JENKINS] Remove Spark from IT Services

docker/docker-entrypoint.sh
=> Fix docker entry point to enable akka http

dist/src/main/resources/server/server-application.conf, dist/src/main/resources/shell/driver-application.conf, driver/src/main/scala/com/stratio/crossdata/driver/JavaDriver.scala, server/src/main/resources/server-reference.conf
=> [JAVA DRIVER][API] Add akka http constructors

core/pom.xml
This is a temporary solution. Once the conflict is fixed, the appender will be removed
=> [CROSSDATA-721] Fix reference conf conflicts

core/src/main/resources/core-reference.conf, core/src/main/scala/org/apache/spark/sql/crossdata/config/CoreConfig.scala, core/src/main/scala/org/apache/spark/sql/crossdata/session/XDSessionProvider.scala, core/src/test/scala/org/apache/spark/sql/crossdata/authorizer/XDAuthorizationIT.scala, dist/src/main/resources/server/core-application.conf
=> Add security.manager.enabled configuration

driver/src/main/scala/com/stratio/crossdata/driver/config/DriverConf.scala
Added methods for easy integration with TLS in DriverConf
=> Added to driverConf the methods for TLS

core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/execution/commands.scala, core/src/test/scala/org/apache/spark/sql/crossdata/execution/datasources/CreateTableIfNotExistsIT.scala
Supporting "if not exists" that previously throwed an exception for "CREATE TABLE"
=> [CROSSDATA-807] Create table if not exists

common/src/main/scala/com/stratio/crossdata/common/result/responses.scala, driver/src/main/scala/com/stratio/crossdata/driver/shell/BasicShell.scala
Added timeout as argument to the shell (--timeout-in-seconds) that controls the time inverted by a query in the server.
=> [CROSSDATA-715] Added timeout for shell

core/src/test/scala/org/apache/spark/sql/crossdata/XDContextIT.scala
One test added for checking the lack of support for subqueries in filters
=> [CROSSDATA-729] Tests for lack of support for subqueries in filter

dist/src/main/resources/server/server-application.conf
Entries for host and port in SSL are not used
=> Removed entries that are not used

CHANGELOG.md, common/src/main/scala/com/stratio/crossdata/common/result/responses.scala, core/src/main/scala/org/apache/spark/sql/crossdata/XDContext.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/analysis/DistinctAggregationRewriterXD.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/execution/commands.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/parser/CrossdataSqlParser.scala, core/src/test/scala/org/apache/spark/sql/crossdata/XDContextIT.scala, core/src/test/scala/org/apache/spark/sql/crossdata/catalyst/analysis/XDResolveReferencesIT.scala, core/src/test/scala/org/apache/spark/sql/crossdata/execution/datasources/CreateTableIfNotExistsIT.scala, driver/src/main/scala/com/stratio/crossdata/driver/config/DriverConf.scala, driver/src/main/scala/com/stratio/crossdata/driver/shell/BasicShell.scala, pom.xml
=> Merge master into branch 1.7

.jenkins.yml, CHANGELOG.md, pom.xml
Updated versions of curator and stratio-commons-utils
=> Updated commons and curator

elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/DefaultSourceESSpec.scala
=> ES_HOST updated to ES_NODES

common/src/main/scala/com/stratio/crossdata/common/serializers/RowSerializer.scala, common/src/test/scala/com/stratio/crossdata/common/serializers/RowSerializerSpec.scala
=> [CROSSDATA-808] Fix Map<Timestamp, String> serialization

driver/src/main/scala/com/stratio/crossdata/driver/shell/BasicShell.scala
This PR fixes the issue that muted the basic shell
=> [CROSSDATA] [SHELL] Fix issue with muted shell

common/src/main/scala/com/stratio/crossdata/common/messages.scala, common/src/main/scala/com/stratio/crossdata/common/serializers/CommandSerializer.scala, common/src/test/scala/com/stratio/crossdata/common/serializers/CommandEnvelopeSpec.scala, common/src/test/scala/com/stratio/crossdata/common/serializers/CommandSerializerSpec.scala, driver/src/main/scala/com/stratio/crossdata/driver/ClusterClientDriver.scala, driver/src/main/scala/com/stratio/crossdata/driver/Driver.scala, driver/src/main/scala/com/stratio/crossdata/driver/HttpDriver.scala, driver/src/main/scala/com/stratio/crossdata/driver/actor/ProxyActor.scala, server/src/main/scala/com/stratio/crossdata/server/CrossdataHttpServer.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ResourceManagerActor.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala
This PR moves the username of the session from CommandEnvelope to OpenSessionCommand
=> Moving user to OpenSessionCommand

zeppelin/pom.xml, zeppelin/src/main/resources/interpreter-setting.json, zeppelin/src/main/scala/org/apache/zeppelin/crossdata/CrossdataInterpreter.scala
This PR adds the required changes to integrate the Crossdata interpreter for Zeppelin into the Stratio PaaS Universe.
=> [CROSSDATA-819] [ZEPPELIN] Zeppelin module adaptations for PaaS Universe

postgresql/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/PostgresqlXDRelation.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlJoinIT.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlSubqueryIT.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlWithSharedContext.scala
=> Test IT for native Join and Subquery

postgresql/src/main/scala/com/stratio/crossdata/connector/postgresql/DefaultSource.scala, postgresql/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/PostgresqlXDRelation.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlCreateExternalTableIT.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlDropExternalTableIT.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlImportTablesIT.scala
CREATE EXTERNAL TABLE
DROP EXTERNAL TABLE
=> Table manipulation operations

Jenkinsfile
=> [QA-288] new Jenkinsfile

Jenkinsfile
=> crossbuild parameter for pkg folder

Jenkinsfile
=> single crossbuild

postgresql/src/main/scala/com/stratio/crossdata/connector/postgresql/DefaultSource.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlInsertCollection.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlInsertTableIT.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlWithSharedContext.scala
=> CreateRelationProvider and Insert test IT

CHANGELOG.md, dist/src/main/resources/server/server-application.conf, dist/src/main/resources/shell/driver-application.conf, driver/src/main/resources/driver-reference.conf, driver/src/main/scala/com/stratio/crossdata/driver/HttpDriver.scala, driver/src/main/scala/com/stratio/crossdata/driver/config/DriverConf.scala, server/src/main/resources/server-reference.conf, server/src/main/scala/com/stratio/crossdata/server/CrossdataHttpServer.scala, server/src/main/scala/com/stratio/crossdata/server/config/ServerConfig.scala
=> [DCS-499] Make http timeouts configurable

docker/catalog-config.sh, docker/crossdata-config.sh, server/src/main/scala/com/stratio/crossdata/server/ServiceDiscoveryProvider.scala
This PR adds improvements in the docker entry point files
=> Cherry picks before branch 1.8

postgresql/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/PostgresqlQueryProcessor.scala, postgresql/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/PostgresqlRDD.scala, postgresql/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/PostgresqlXDRelation.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlRDDFilterSpec.scala
PostgresqlRDD to improve filter pushdown
=> PostgresqlRDD with filter pushdown

driver/src/main/scala/com/stratio/crossdata/driver/shell/BasicShell.scala, driver/src/main/scala/com/stratio/crossdata/driver/shell/ShellArgsReader.scala, driver/src/test/scala/com/stratio/crossdata/driver/shell/ShellArgsReaderSpec.scala
Ability to execute a query specified with the option --query.
The shell will execute that query, show the result on the standard output and exit.
=> Executing query from the shell

core/src/main/scala/com/stratio/crossdata/connector/interfaces.scala, core/src/main/scala/org/apache/spark/sql/crossdata/XDDataFrame.scala, postgresql/src/main/scala/com/stratio/crossdata/connector/postgresql/DefaultSource.scala, postgresql/src/main/scala/org/apache/spark/sql/catalyst/ExpressionsSQLBuilder.scala, postgresql/src/main/scala/org/apache/spark/sql/catalyst/SQLBuilder.scala, postgresql/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/PostgresqlQueryProcessor.scala, postgresql/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/PostgresqlRelationUtils.scala, postgresql/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/PostgresqlUtils.scala, postgresql/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/PostgresqlXDRelation.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlAggregationIT.scala, postgresql/src/test/scala/com/stratio/crossdata/connector/postgresql/PostgresqlCreateExternalTableIT.scala, server/pom.xml
- Review changes
- Add connector dependency to server pom
=> [Postgresql connector] Changes after review

core/src/main/scala/org/apache/spark/sql/crossdata/XDSession.scala, core/src/test/resources/zookeeper-catalog.conf, core/src/test/scala/org/apache/spark/sql/crossdata/XDSessionIT.scala
Enhance XDSession builder to load configuration from Typesafe Config files.
=> [CROSSDATA-910] Introduce core configuration file values into SQLConf/SparkConf before creating sessions

pom.xml
=> Upgrade Common Utils & Curator

core/src/test/scala/org/apache/spark/sql/crossdata/catalyst/catalog/persistent/zookeeper/ZookeeperCatalogIT.scala
This PR adds database management testing for Zookeeper external catalog implementation
=> [CROSSDATA-897] Zookeeper external catalog tests: Databases registration and management

Jenkinsfile, core/src/main/scala/org/apache/spark/sql/crossdata/XDSession.scala, core/src/test/resources/zookeeper-catalog.conf
=> Fix Zookeeper IT

core/src/test/resources/zookeeper-catalog.conf
=> Fix properties subtitution

core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/catalog/persistent/zookeeper/ZookeeperCatalog.scala, core/src/test/resources/catalogspec/zookeeper-catalog-test-properties.conf, core/src/test/scala/org/apache/spark/sql/crossdata/XDSessionIT.scala
This PR fix the list table services provided by Zookeeper catalog. Previous to the changes hereby added, name regular expressions were not correctly applied.
It also adds concurrency protection in the catalog implementation.
=> [CROSSDATA-897] Zookeeper catalog fixes and improvements.

core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/catalog/persistent/models/TableModel.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/catalog/persistent/zookeeper/ZookeeperCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/catalog/persistent/zookeeper/daos/TableDAO.scala, core/src/test/scala/org/apache/spark/sql/crossdata/catalyst/catalog/persistent/zookeeper/ZookeeperCatalogIT.scala, pom.xml
=> Zookeeper catalog partition test

core/src/main/scala/org/apache/spark/sql/crossdata/execution/XDQueryExecution.scala, core/src/test/scala/org/apache/spark/sql/crossdata/DataFrameIT.scala
Temporarily, disable native execution when executing DataSet's collect.
=> [DCS-2035][Core] Disable XDPlan

Jenkinsfile
=> proper variable name
