crossdata-cassandra/src/main/scala/com/stratio/crossdata/sql/sources/cassandra/CassandraQueryProcessor.scala, crossdata-cassandra/src/main/scala/org/apache/spark/sql/cassandra/CassandraXDSourceRelation.scala, crossdata-examples/src/main/scala/com/stratio/crossdata/examples/CassandraExample.scala
added a simple validation to cassandra filters to check if the filter is a cluster key column, then all columns of cluster key must appear in filters to execute in a native way, in other cases the execution will be through spark cluster
=> New generation. Validate Cassandra native filters

crossdata-ng/src/main/scala/org/apache/spark/sql/crossdata/XDContext.scala, crossdata-ng/src/main/scala/org/apache/spark/sql/sources/crossdata/XDDdlParser.scala, crossdata-ng/src/main/scala/org/apache/spark/sql/sources/crossdata/ddl.scala, crossdata-ng/src/test/scala/org/apache/spark/sql/crossdata/XDContextIT.scala, crossdata-ng/src/test/scala/org/apache/spark/sql/sources/crossdata/XDDdlParserSpec.scala
This branch contains the changes that endow `XDContext` with a customized DDL parser which initially parses sentences matching the pattern: 
`IMPORT CATALOG USING <package. ... .subpackage.class> OPTIONS ( optname "value", ...)`
It remains to be completed the implementation of, the `RunnableCommand`, `ImportCatalogUsingWithOptions` with its functionality.
=> Cd856 new ddlsentences

crossdata-cassandra/src/main/scala/com/stratio/crossdata/sql/sources/cassandra/DefaultSource.scala, crossdata-cassandra/src/main/scala/org/apache/spark/sql/cassandra/CassandraXDSourceRelation.scala, crossdata-cassandra/src/test/scala/com/stratio/crossdata/sql/sources/cassandra/CassandraConnectorIT.scala, crossdata-cassandra/src/test/scala/com/stratio/crossdata/sql/sources/cassandra/CassandraWithSharedContext.scala, crossdata-ng/src/main/scala/com/stratio/crossdata/sql/sources/interfaces.scala, crossdata-ng/src/main/scala/org/apache/spark/sql/sources/crossdata/XDDdlParser.scala, crossdata-ng/src/main/scala/org/apache/spark/sql/sources/crossdata/ddl.scala, crossdata-ng/src/test/scala/org/apache/spark/sql/crossdata/XDContextIT.scala, crossdata-ng/src/test/scala/org/apache/spark/sql/sources/crossdata/XDDdlParserSpec.scala, doc/src/site/sphinx/GrammarExp.rst, doc/src/site/sphinx/about.rst
This pull request includes the implementation of the already recognized `IMPORT CATALOG` sentence for the C* connector.
It also provides with interfaces and examples for new implementations of tables and catalogs imports from any compatible connector. Any new relation being able of exploring datasources schemes should implement the `TableInventory` interface.
=> Cd856 action with provideriface

mongodb/src/main/scala/com/stratio/crossdata/connector/mongodb/MongoQueryProcessor.scala, mongodb/src/test/scala/com/stratio/crossdata/connector/mongodb/MongoConnectorIT.scala
The same semantic should be applied for all connectors. So, although a limit 0 in MongoDB returns all the rows we should return no rows,
=> [CROSSDATA-76] [MongoDB] Fix queries with LIMIT 0

core/src/main/scala/org/apache/spark/sql/sources/crossdata/ddl.scala
Persisted options didn't include generated opts when importing tables
=> [CROSSDATA-86] [CORE] Fix critical bug: persisted options didn't include generated opts

pom.xml
New profile in pom parent for support zinc compilation.
On the shell we can execute: mvn clean package -Pzinc
Previous we must run zinc server on the machine:
zinc-0.3.7/bin/zinc -quiet -start
@miguel0afd 
All passed.
No changes
No info
=> New profile for zinc compilation

common/src/main/scala/com/stratio/crossdata/common/Messages.scala, common/src/main/scala/com/stratio/crossdata/common/result/SQLResult.scala, core/src/main/scala/org/apache/spark/sql/crossdata/XDDataFrame.scala, core/src/test/scala/org/apache/spark/sql/crossdata/test/SharedXDContextTypesTest.scala, driver/src/main/scala/com/stratio/crossdata/driver/actor/ProxyActor.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala
Added an `annotatedCollect` method which wraps `XDDataFrame#collect` method to provide a list of fully annotated column names. e.g: `List("col.subfield.subsubfield")`
=> Full flattened columns

core/src/main/scala/org/apache/spark/sql/crossdata/XDDataFrame.scala
`SELECT *` queries do not generate `Project` plans therefore, the logical plan lacks information describing the selection schema. For those cases, the flattened column description is generated using the `Row`s schema.
However, some data sources do not provide that schema when used to run queries natively (avoiding Spark).
This PR forces project-less queries to be run through Spark in order to force `Row`s to have information describing the result schema.
=> Force Spark execution when the query logical plan has not any projection

README.rst
Obsolete Github documentation removed
Github documentation redirects users to Confluence
=> Documentation refactor

common/src/main/scala/com/stratio/crossdata/common/result/SQLResult.scala, core/src/main/scala/org/apache/spark/sql/crossdata/XDDataFrame.scala, core/src/test/scala/org/apache/spark/sql/crossdata/test/SharedXDContextTypesTest.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala
`annotatedCollect` has been changed to `flattenedCollect` which implies that `SuccessfulQueryAnnotatedResult` server answer disappears.
`annotatedCollect` result now always contains a fully flattened schema where
each column name is also fully qualified.
=> Flattened Collect

server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala
Instead of using the first returned row schema, it will be used the longest row's in order to improve the global schema flattened approximation.
=> Flattened Collect: Use wider row flattened schema as results schema

server/src/main/resources/server-reference.conf
This means that the cluster leader member will change the unreachable node status to down automatically after the configured time of unreachability.
=> Autodown node

core/src/main/resources/core-reference.conf, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/DerbyCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/JDBCCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/XDCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/ZookeeperCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/execution/datasources/XDDdlParser.scala, core/src/main/scala/org/apache/spark/sql/crossdata/execution/datasources/ddl.scala, core/src/test/scala/org/apache/spark/sql/crossdata/catalog/GenericCatalogTests.scala, core/src/test/scala/org/apache/spark/sql/crossdata/execution/datasources/ViewsIT.scala, core/src/test/scala/org/apache/spark/sql/crossdata/execution/datasources/XDDdlParserSpec.scala
- Core implementation of persisted views 
- Derby and JDBC implementation
- Catalog refactor
Zookeeper implementation is blocked by some improvements in common-utils.
=> [CROSSDATA-236][CROSSDATA-237] Support persisted views in Spark

cassandra/src/test/scala/com/stratio/crossdata/connector/cassandra/CassandraTypesIT.scala, core/src/main/scala/org/apache/spark/sql/crossdata/XDDataFrame.scala, core/src/test/scala/org/apache/spark/sql/crossdata/test/SharedXDContextTypesTest.scala, mongodb/src/test/scala/com/stratio/crossdata/connector/mongodb/MongoDataTypesCollection.scala, mongodb/src/test/scala/com/stratio/crossdata/connector/mongodb/MongoWithSharedContext.scala
With this, `flattenedCollect` performs a bi-dimensional flattening thus removing structures as fields as well as arrays.  The former kind of flattening is the horizontal one whereas the latter is done vertically, that is: Each array element makes the row to be duplicated in a new row where the array is replaced by the element itself.
=> [CROSSDATA-257][CD] Flattened arrays

cassandra/src/test/scala/com/stratio/crossdata/connector/cassandra/CassandraTypesIT.scala, core/src/test/scala/org/apache/spark/sql/crossdata/test/SharedXDContextTypesTest.scala
Fixed `SparkSQLColdDef` identifier typo error. It should be `SparkSQLColDef`
=> Fix typo error

core/src/main/scala/org/apache/spark/sql/crossdata/XDDataFrame.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala
Bug fixes:
- When a row lacked any array column it was getting deleted.
- Flattened limit wasn't being correctly applied.
- Because of the way the result schema was being calculated, `SHOW TABLES` queries failed when executed using the driver.
=> Fix arrayless flatdeletion

core/src/main/scala/org/apache/spark/sql/crossdata/XDContext.scala
`FunctionInventory` instances should be annotated as transient within `XDContext` since they are provided by connector instances which are not serializable
=> Fixed "NotSerializableException" when R uses Crossdata with its datasources.

driver/src/main/scala/com/stratio/crossdata/driver/actor/ProxyActor.scala
Temporary tables creation queries get distributed to all servers so local catalog caches are synchronized
This approach is temporary (as the tables it addresses) and should be changed ASAP
=> [CROSSDATA-348] Naive table cache synchronization

core/src/main/scala/org/apache/spark/sql/crossdata/catalog/XDCatalog.scala, core/src/test/scala/org/apache/spark/sql/crossdata/catalog/GenericCatalogTests.scala, core/src/test/scala/org/apache/spark/sql/crossdata/execution/datasources/ViewsIT.scala
This PR restrict the creation of views over previously persisted tables only.
=> [CROSSDATA-371] Restrict create view over a temporary table

server/src/main/scala/com/stratio/crossdata/server/actors/JobActor.scala
The prolific ExecutionContext wasn't being used at the right place so the problem it was aimed to fix (spark failures because the same thread was being used for different collect calls) was still there.
=> Use prolific execution context to run the spark-driver code

server/src/main/scala/com/stratio/crossdata/server/CrossdataServer.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala, server/src/main/scala/com/stratio/crossdata/server/config/ServerActorConfig.scala
Instead of reading the server config file for every instance of the Server Actor, the file is read only once and a few parameters of them are passed to every instance of the Server Actor.
=> [CROSSDATA-367] [SERVER] Server config file is now loaded only once

mongodb/src/test/scala/com/stratio/crossdata/connector/mongodb/MongoQueryProcessorSpec.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala, streaming/src/test/scala/com/stratio/crossdata/streaming/kafka/KafkaInputSpec.scala
- Changed non-idiomatic exception expectation at test
- Removed type-erasured checks
- Remove wrong `Receive` function branch
Yet to be fixed those generated by scala:doc because it can't find spark-sql document jar.
=> [CROSSDATA-412] Compilation-time warnings fixes

core/src/main/resources/core-reference.conf, core/src/main/scala/com/stratio/crossdata/launcher/SparkJobLauncher.scala, core/src/main/scala/org/apache/spark/sql/crossdata/config/StreamingConstants.scala, dist/src/main/resources/server/core-application.conf
SparkJobLauncher.setDeployMode("cluster") was not working as expected, so it has been replaced with the spark arg --deploy-mode
reviewer @miguel0afd
=> [CROSSDATA-299] [STREAMING] Support client and cluster mode

elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticWithSharedContext.scala
- Avoiding collision between names of tests with Scala 2.10 & 2.11
=> [CROSSDATA] [ES] [TESTS] ES Tests fixed

core/src/main/resources/core-reference.conf, core/src/test/resources/core-reference.conf, dist/pom.xml, dist/src/main/resources/server/core-application.conf
Streaming-fat-jar should not be a dependency but an application-jar for spark. Thus, it has been removed from /opt/sds/crossdata/lib.
=> [CROSSDATA-459] Solve dependency conflicts in deb/rpm

driver/src/main/scala/com/stratio/crossdata/driver/config/DriverConf.scala
A call to parseResources with "external.config.resource" have been replaced with the value of external.config.resource. Anyway, I have doubts about what it is used for.
=> [DriverConf] [Minor] Config resource filename should not be hard-coded

core/src/main/scala/org/apache/spark/sql/crossdata/execution/datasources/XDDdlParser.scala, core/src/test/scala/org/apache/spark/sql/crossdata/execution/datasources/XDDdlParserSpec.scala
Before this PR, inserting empty arrays or map syntax was rather counter intuitive. Now, it is as easy as passing `[]` and `()` values for empty arrays and maps respectively. 
- Unit tests has been added to check whether this change has been properly applied.
=> [CROSSDATA-465] Now it is possible to insert empty arrays and maps

.jenkins.yml, CHANGELOG.md, cleanDerbyDBs.sh, common/src/main/scala/com/stratio/crossdata/common/result/results.scala, elasticsearch/pom.xml, elasticsearch/src/main/scala/com/stratio/crossdata/connector/elasticsearch/DefaultSource.scala, elasticsearch/src/main/scala/com/stratio/crossdata/connector/elasticsearch/ElasticSearchConnectionUtils.scala, elasticsearch/src/main/scala/com/stratio/crossdata/connector/elasticsearch/ElasticSearchQueryProcessor.scala, elasticsearch/src/main/scala/com/stratio/crossdata/connector/elasticsearch/ElasticSearchRowConverter.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticSearchConnectionUtilsIT.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticSearchCreateExternalTableIT.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticSearchImportTablesIT.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticSearchQueryProcessorSpec.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticSearchTypesIT.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticWithSharedContext.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticsearchConnectorIT.scala, examples/src/main/scala/com/stratio/crossdata/examples/driver/CassandraExample.scala, streaming/src/main/scala/com/stratio/crossdata/streaming/helpers/CrossdataStreamingHelper.scala, streaming/src/test/scala/org/apache/spark/streaming/kafka/CrossdataStreamingHelperProjectIT.scala
This PR allows to work with Elasticsearch 2.3
The dependency of the elastic4s has been upgraded from 1.7 to 2.3
=> [CROSSDATA-512] [ELASTICSEARCH] Upgrade to 2.3

.gitignore, .jenkins.yml, core/src/main/scala/com/stratio/crossdata/util/CacheInvalidator.scala, core/src/main/scala/org/apache/spark/sql/crossdata/XDSessionProvider.scala, core/src/main/scala/org/apache/spark/sql/crossdata/catalog/temporary/XDTemporaryCatalogWithInvalidation.scala, core/src/main/scala/org/apache/spark/sql/crossdata/execution/datasources/XDDdlParser.scala, project/build.properties, project/build.scala, project/plugins.sbt, server/src/main/scala/org/apache/spark/sql/crossdata/catalog/persistent/HazelcastCacheInvalidator.scala, server/src/main/scala/org/apache/spark/sql/crossdata/session/HazelcastSessionProvider.scala, server/src/main/scala/org/apache/spark/sql/crossdata/session/SessionResourceManager.scala, server/src/test/scala/org/apache/spark/sql/crossdata/session/HazelcastSessionCatalogManagerSpec.scala, server/src/test/scala/org/apache/spark/sql/crossdata/session/HazelcastSessionProviderSpec.scala
This PR adds the building blocks for local per-session-resource cache invalidation within the cluster and uses them to implement a hazelcast-topic based invalidator for session in memory catalogs.
=> Resource local caches invalidation

elasticsearch/src/main/scala/com/stratio/crossdata/connector/elasticsearch/DefaultSource.scala, elasticsearch/src/main/scala/com/stratio/crossdata/connector/elasticsearch/ElasticSearchConnectionUtils.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticSearchDropExternalTableIT.scala
If just one type exist in the Index we are able to delete it by removing all the index, if not the user is notified by an exception.
=> [CROSSDATA-544]Working ES preventing remove tables

common/src/main/scala/com/stratio/crossdata/common/messages.scala, driver/src/main/scala/com/stratio/crossdata/driver/Driver.scala, driver/src/main/scala/com/stratio/crossdata/driver/actor/ProxyActor.scala, server/src/main/scala/com/stratio/crossdata/server/CrossdataHttpServer.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ResourceManagerActor.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala
A mechanism to link session ids to user ids is needed. Since the client will be considered a trusted agent (indeed it is the client who generates the session id) and the channel integrity will be guaranteed, there is no problem in sending the user along side the session id within each `CommandEnvelope` message. Thus reducing the boilerplate this functionality would require if a relation table were keep at server side.
=> [CROSSDATA-588] Each command envelope now includes the user associated to the session.

core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/execution/commands.scala, server/src/test/scala/com/stratio/crossdata/server/CrossdataAvroIT.scala, server/src/test/scala/com/stratio/crossdata/server/CrossdataCSVIT.scala, server/src/test/scala/com/stratio/crossdata/server/CrossdataDdlIT.scala
The schema of tables created using 'CREATE TABLE ... AS SELECT' was not persisted, so although data were inserted, the user did not be able to perform queries since the new table has no schema.
=> [CROSSDATA-593] Improve 'CREATE TABLE AS SELECT' statements' behaviour

.jenkins.yml
This constraint comes from the fact that, soon, we'll be using Akka 2.4+ which is not binary compatible with Scala 2.10
=> Removed Jenkins' crossbuild as we are abandoning Scala 2.10 support

.jenkins.yml, CHANGELOG.md, elasticsearch/pom.xml, elasticsearch/src/main/scala/org/elasticsearch/spark/sql/ElasticsearchXDRelation.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticDataTypesWithSharedContext.scala, elasticsearch/src/test/scala/com/stratio/crossdata/connector/elasticsearch/ElasticSearchNewTypesIT.scala
New changes at the elastic data source allow us to get rid off many copy-paste lines within Crossdata connector. 
It also adds a bug fix enabling the BINARY field type.
=> Update elasticsearch-hadoop data source version to 2.4.0

driver/pom.xml
Delete dependency with the akka protobuf due to akka upgrade. Not necessary anymore.
=> Delete dependency with the akka protobuf due to akka upgrade

docker/docker-entrypoint.sh
After merging this PR Crossdata will be launched as an application within the docker, not as an INIT daemon. That makes its output to be correctly redirected to cluster managers as well as the docker container be stopped if the server crashes.
If the docker is run with the option `-e SERVER_MODE=debug` it will launch Crossdata as a service within the docker container, that is, as before the PR was merged.
=> [CROSSDATA-646] Crossdata as runs as an application instead as an Upstart service within docker.

docker/docker-entrypoint.sh
After merging this PR Crossdata will be launched as an application within the docker, not as an INIT daemon. That makes its output to be correctly redirected to cluster managers as well as the docker container be stopped if the server crashes.
If the docker is run with the option -e SERVER_MODE=debug it will launch Crossdata as a service within the docker container, that is, as before the PR was merged.
=> [CROSSDATA-646] Crossdata as runs as an application instead as an Upstart service within docker. 

docker/docker-entrypoint.sh
The docker entry point now also reacts to the presence of XD_EXTERNAL_IP by adding an alias from its values to the docker exposed ip at /etc/hosts.
It is also sensitive to the variable HAPROXY_SERVER_INTERNAL_ADDRESS. If present, the aliased IP will be its value instead of the docker exposed IP thus allowing HA Proxy loop.
=> [CROSSDATA-649] Network params docker entry point

core/src/main/scala/org/apache/spark/sql/crossdata/XDSession.scala
=> [CROSSDATA-658] Mark catalog and config fields as transient

server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala
When a session is not found and this way an error result is returned, it should be wrapped by a SQLReplay object.
=> Bug fix: Unwrapped error result when the session is closed

driver/src/main/scala/com/stratio/crossdata/driver/JavaDriver.scala
This PR adds the method serversUp to the Java Driver in order to have information about the nodes forming the Crossdata cluster.
=> serversUp method available in the Java Driver

dist/src/main/resources/shell/driver-application.conf, driver/src/main/resources/driver-reference.conf, driver/src/main/scala/com/stratio/crossdata/driver/Driver.scala, driver/src/main/scala/com/stratio/crossdata/driver/config/DriverConf.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/TLSAuthInvalidCertificateIT.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/TLSAuthValidCertificateIT.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/config/DriverConfSpec.scala
This PRs improve HTTP Driver Java compatibility by including new factory methods & config helpers for setting HTTP host & port.
=> Update driver config

driver/src/main/scala/com/stratio/crossdata/driver/shell/BasicShell.scala
This PR solves the problem with the arguments of the Basic Shell  script. It is possible to add to the basic shell two arguments:
--user username
--http true/false
=> Fix shell arguments

core/src/test/scala/org/apache/spark/sql/crossdata/XDContextIT.scala
=> Cherrypick with branch 1.7 for tests

server/src/main/resources/server-reference.conf, server/src/main/scala/com/stratio/crossdata/server/CrossdataServer.scala, server/src/main/scala/com/stratio/crossdata/server/config/ServerConfig.scala, testsIT/src/test/resources/server-application.conf
Disabled ClusterClient(TCP) by default. If you want to enable Cluster client set:
crossdata-server.config.cluster-client.enabled = true
=> Disabled TCP by default

server/src/main/scala/com/stratio/crossdata/server/CrossdataApplication.scala, server/src/main/scala/com/stratio/crossdata/server/CrossdataServer.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ResourceManagerActor.scala, server/src/main/scala/com/stratio/crossdata/server/actors/ServerActor.scala, server/src/main/scala/com/stratio/crossdata/server/config/ServerConfig.scala, server/src/test/scala/com/stratio/crossdata/server/CrossdataAvroIT.scala, server/src/test/scala/com/stratio/crossdata/server/CrossdataCSVIT.scala, server/src/test/scala/com/stratio/crossdata/server/CrossdataDdlIT.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/EndToEndTest.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/MongoWithSharedContext.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/TLSAuthInvalidCertificateIT.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/TLSAuthNoCertificateIT.scala, testsIT/src/test/scala/com/stratio/crossdata/driver/TLSAuthValidCertificateIT.scala
Changing the inheritance of "ServerConfig" to a composition pattern
=> [CROSSDATA-818]Removed Server config as trait

common/src/main/scala/com/stratio/crossdata/common/serializers/RowSerializer.scala, common/src/test/scala/com/stratio/crossdata/common/serializers/RowSerializerSpec.scala
Spark inferences a PARQUET double column schema type as a DecimalType column when it should be Double. The serializer didn't expect this behavior and this PR adds safeguards to avoid failures.
=> RowSerializer: Safe guard against double types with Decimal schema tags

core/src/main/scala/org/apache/spark/sql/crossdata/XDDatasetFunctions.scala, core/src/main/scala/org/apache/spark/sql/crossdata/XDSession.scala, core/src/main/scala/org/apache/spark/sql/crossdata/session/XDSessionState.scala, core/src/test/scala/org/apache/spark/sql/crossdata/XDSessionIT.scala, pom.xml
This PR provides a way of building Crossdata sessions without Spark's `getOrElse` and requiring the user associated with it. Besides, it adds a session id generation in the session constructor which remove the responsibility of generating it from the client.
Additionally
=> [CROSSDATA-883] XDSessionProvider: Code simplification, session factory (for provided users) & session id.

core/src/main/scala/org/apache/spark/sql/crossdata/XDDatasetFunctions.scala, core/src/test/scala/org/apache/spark/sql/crossdata/DataFrameIT.scala, core/src/test/scala/org/apache/spark/sql/crossdata/Person.scala
This PR check that all functions now are accessible from xddataset, like native collect.
=> [CROSSDATA-849][SPARK 2.1] Keep XDDataFrameFunctions

core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/catalog/XDSessionCatalog.scala, core/src/main/scala/org/apache/spark/sql/crossdata/session/XDSessionState.scala
Through XDSessionState, our custom session catalog overrides default Spark 2.1 implementation thus enabling a point of extension.
=> [CROSSDATA-858] Wiring custom XDSessionCatalog into XDSession

core/src/main/scala/org/apache/spark/sql/crossdata/catalyst/catalog/persistent/zookeeper/ZookeeperCatalog.scala, core/src/test/scala/org/apache/spark/sql/crossdata/XDSessionIT.scala
These changes protect against failures when listing tables in new environment where no catalog entities were previously created.
=> [DCS-2033] Fixed crash when pristine zookeeper backends were asked to list tables
